### ISSUE TITLE
404! 😱

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/WaitlistApp#1]
I'm all mixed up. I wrote my Rails app with Angular and then tried to copy an old homework example for my MEAN app, and I'm getting a 404:

"angular.js:11756 GET http://localhost:8080/api/parties 404 (Not Found)"

The offending code in my partiesAPI.js service:

angular.module('PartiesAPI', [])
       .factory('partiesAPI', ['$http', function( $http ) {
         return {

```
   getAll: function() {
     return $http.get('/api/parties');
   },

   save: function(newParty) {
     return $http.post('/api/parties', newParty);
   },

   remove: function(id) {
     return $http.delete('/api/parties/' + id);
   }
 }
```

But it looks to me like I've replicated everything from our past example.

**Comment by DZGoldman** [comment]
Oy - is the code in question on github?

**Comment by rachelhamlin** [comment]
Noooo. And I just broke it again. I'll push it now.

On Thu, May 26, 2016 at 2:34 PM, Daniel Goldman notifications@github.com
wrote:

> Oy - is the code in question on github?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rachelhamlin/WaitlistApp/issues/1#issuecomment-221956390

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by rachelhamlin** [comment]
Actually...yes, that code WAS on Github. And I'm going to leave it, because
I made it worse

On Thu, May 26, 2016 at 2:37 PM, Rachel Hamlin rachelmhamlin@gmail.com
wrote:

> Noooo. And I just broke it again. I'll push it now.
> 
> On Thu, May 26, 2016 at 2:34 PM, Daniel Goldman notifications@github.com
> wrote:
> 
> > Oy - is the code in question on github?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/rachelhamlin/WaitlistApp/issues/1#issuecomment-221956390
> 
> ## 
> 
> Rachel Hamlin
> (315) 525-0537
> LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
> https://twitter.com/rachelhamlin

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by rachelhamlin** [comment]
Update: I made it better and the 404 is solved, but I'm still not seeing
any data. Pushing latest...

On Thu, May 26, 2016 at 2:37 PM, Rachel Hamlin rachelmhamlin@gmail.com
wrote:

> Actually...yes, that code WAS on Github. And I'm going to leave it,
> because I made it worse
> 
> On Thu, May 26, 2016 at 2:37 PM, Rachel Hamlin rachelmhamlin@gmail.com
> wrote:
> 
> > Noooo. And I just broke it again. I'll push it now.
> > 
> > On Thu, May 26, 2016 at 2:34 PM, Daniel Goldman <notifications@github.com
> > 
> > > wrote:
> > > 
> > > Oy - is the code in question on github?
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/rachelhamlin/WaitlistApp/issues/1#issuecomment-221956390
> > 
> > ## 
> > 
> > Rachel Hamlin
> > (315) 525-0537
> > LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
> > https://twitter.com/rachelhamlin
> 
> ## 
> 
> Rachel Hamlin
> (315) 525-0537
> LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
> https://twitter.com/rachelhamlin

## 

Rachel Hamlin
(315) 525-0537
LinkedIn http://www.linkedin.com/in/rachelhamlin | Twitter
https://twitter.com/rachelhamlin

**Comment by DZGoldman** [comment]
I'm on the couches, come on over

**Comment by rachelhamlin** [comment]
NVM - problem solved! Thanks!
