### ISSUE TITLE
Crazy s*** is happening

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/WaitlistApp#2]
So I had my scripts, styles, and views folder nested inside one too many folders inside my MEAN app (rather than client/views I had client/public/views), and to clean things up & fix a 404 issue, I moved them up and got rid of the public folder.

But, every time I work with one of these files, it recreates the folder and edits the version of it within the public folder. 😳

This is my tree view now:

.
├── app.js
├── client
│   ├── css
│   │   └── styles.css
│   ├── js
│   │   ├── app.js
│   │   ├── controllers
│   │   │   └── partiescontroller.js
│   │   └── services
│   │       └── partiesAPI.js
│   ├── media
│   │   ├── background.jpg
│   │   └── logo.png
│   ├── public
│   │   └── js
│   │       └── controllers
│   │           └── partiescontroller.js
│   └── views
│       └── index.ejs

What's going onnnnnnn

**Comment by rapala61** [comment]
what
